Homework done for lesson 3
zurbaevi/android-popular-libraries pull request #3
Opened 2021-09-20 23:06 UTC by zurbaevi

2021-09-27 15:49 UTC, PeterBukhal-Geekbrains requested changes
Есть критические замечания. Пока не принимаю.

2021-09-27 15:49 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/AndroidScreens.kt
> +class AndroidScreens : IScreens {
Я бы пошел дальше и вовсе разделил бы каждый экран в свой отдельный класс. Иначе придется модифицировать каждый раз когда нужно добавить или удалить, изменить экраны, что может приводить к частым конфликтам при работе над проектом. Так же файл будет разрастаться по мере увеличения количества экранов.

2021-09-27 15:49 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/MainActivity.kt
> +    private var vb: ActivityMainBinding? = null
Удобно использовать https://github.com/kirich1409/ViewBindingPropertyDelegate. См. последний пример с разбором ДЗ урока 2.

2021-09-27 15:49 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/UserFragment.kt
> +    private var vb: FragmentUserBinding? = null
Удобно использовать https://github.com/kirich1409/ViewBindingPropertyDelegate. См. последний пример с разбором ДЗ урока 2.

2021-09-27 15:49 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/UserFragment.kt
> +        fun newInstance(user: GithubUser) =
При создании объектов используя фабрики нужно возвращать максимально базовый тип в иерархии наследования если такая имеется, то есть делать восходящее преобразование. В данном случае к `Fragment`, см. `FragmentScreen` из Cicerone. Это дает больше возможностей по изменению реализации, и явно указывает на то что не следует использовать или ссылаться на тип конкретного фрагмента.

2021-09-27 15:49 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/UserFragment.kt
> +                arguments = Bundle().apply {
Правильней не создавать новый `Bundle`, а пользоваться фабрикой `bundleOf` будет чуть эффективней)

2021-09-27 15:49 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/UsersFragment.kt
> +        fun newInstance() = UsersFragment()
При создании объектов используя фабрики нужно возвращать максимально базовый тип в иерархии наследования если такая имеется, то есть делать восходящее преобразование. В данном случае к `Fragment`, см. `FragmentScreen` из Cicerone. Это дает больше возможностей по изменению реализации, и явно указывает на то что не следует использовать или ссылаться на тип конкретного фрагмента.

2021-09-27 15:49 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/UsersFragment.kt
> +    private var vb: FragmentUsersBinding? = null
Удобно использовать https://github.com/kirich1409/ViewBindingPropertyDelegate. См. последний пример с разбором ДЗ урока 2.

2021-09-27 15:49 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/presenter/UsersPresenter.kt
> +        usersRepo.getUsers().subscribe { users -> usersListPresenter.users.addAll(users) }
Упущен важный момент про который мы говорили на вебинаре, это отмена цепочки в случае необходимости. В текущем виде этот момент не реализован, нужно использовать `Disposable` и отменить цепочку как минимум в методе презентера `onDestroy`.
Хорошей практикой написания реактивных цепочек является написание их в каждой новой строке, это улучшает читаемость.
Хорошая практика это выносить обработчики в отдельные методы, это улучшит читаемость и возможность их переиспользовать. Смотри код урока 3.

2021-09-28 12:22 UTC, PeterBukhal-sovcombank approved these changes
Хорошо, задание выполнено, замечаний нет.

2021-09-28 12:36 UTC, merged

2021-09-28 16:32 UTC, zurbaevi commented
Все замечания были исправлены