Homework done for lesson 4
zurbaevi/android-popular-libraries pull request #4
Opened 2021-09-25 16:47 UTC by zurbaevi

2021-09-27 21:02 UTC, PeterBukhal-Geekbrains requested changes
Давай улучшим работу над реактивом, пока есть проблемы.

2021-09-27 21:02 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/repository/Repository.kt
> +    fun convertJPGtoPNG(file: File): Completable
Очень нелаконичный API уверен, что можно обойтись 1 методом, который на входе получает файл в каком то виде (Uri, URL, путь до файла и тд.) и на выходе возвращает тоже самое, либо ошибку.

2021-09-27 21:02 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/example/android/popularlibraries/presenter/MainPresenterImpl.kt
> +                { it.message?.let { message -> view.showError(message) } })
Хорошая практика это выносить обработчики в отдельные методы, это улучшит читаемость и возможность их переиспользовать. Смотри код урока 3.

2021-09-30 11:41 UTC, merged

2021-10-11 09:55 UTC, zurbaevi commented
Исправил ошибки